apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "rest-api.fullname" .}}-configmap"
data:
  TRAK_SECRET_KEY: "{{ .Values.env.secretKey }}"
  TRAK_CORS_DOMAINS: "{{ .Values.env.corsDomains }}"
  TRAK_RCRAINFO_ENV: "{{ .Values.env.rcraInfoEnv }}"
  CELERY_BROKER_URL: "{{ .Values.env.cache.url }}"
  CELERY_RESULT_BACKEND: "django-db"
  TRAK_DB_HOST: "{{ .Values.env.db.host }}"
  TRAK_DB_PORT: "{{ .Values.env.db.port }}"
  TRAK_DB_NAME: "{{ .Values.env.db.name }}"
  TRAK_DB_USER: "{{ .Values.env.db.user }}"
  TRAK_DB_PASSWORD: "{{ .Values.env.db.password }}"
  TRAK_DB_ENGINE: "{{ .Values.env.db.engine }}"
