# Generated by Django 4.2.7 on 2023-11-12 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_haztrakprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='haztrakprofile',
            name='rcrainfo_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='haztrak_profile', to='core.rcraprofile'),
        ),
    ]
