# Generated by Django 5.0.4 on 2024-06-30 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_authority_role_userrole'),
        ('site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authority',
            name='content_type',
        ),
        migrations.AddField(
            model_name='userrole',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='site.site'),
            preserve_default=False,
        ),
    ]
