# Generated by Django 4.2.7 on 2023-11-12 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_haztrakprofile_rcrainfo_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haztrakprofile',
            name='rcrainfo_profile',
        ),
        migrations.AddField(
            model_name='rcraprofile',
            name='haztrak_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rcrainfo_profile', to='core.haztrakprofile'),
        ),
    ]
