# Generated by Django 4.2.7 on 2023-11-12 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_haztrakprofile_rcrainfo_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rcraprofile',
            name='haztrak_profile',
        ),
        migrations.AddField(
            model_name='haztrakprofile',
            name='rcrainfo_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='haztrak_profile', to='core.rcraprofile'),
        ),
    ]
