# Generated by Django 4.2.7 on 2023-11-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_rcraprofile_haztrak_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rcraprofile',
            name='user',
        ),
    ]
