# Generated by Django 4.2.7 on 2023-11-11 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_haztrakorg_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haztraksite',
            name='admin_rcrainfo_profile',
        ),
        migrations.AddField(
            model_name='haztraksite',
            name='org',
            field=models.ForeignKey(default='efb9e104-7f61-4365-a9af-9d7b55c854c4', on_delete=django.db.models.deletion.CASCADE, to='sites.haztrakorg'),
            preserve_default=False,
        ),
    ]
