# Generated by Django 4.2.7 on 2023-11-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_remove_haztraksite_admin_rcrainfo_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcrasite',
            name='site_type',
            field=models.CharField(blank=True, choices=[('Generator', 'Generator'), ('Transporter', 'Transporter'), ('Tsdf', 'Tsdf'), ('Broker', 'Broker')], max_length=20, null=True),
        ),
    ]
