# Generated by Django 4.2.7 on 2023-11-13 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_alter_rcrasite_site_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='haztrakorg',
            options={'ordering': ['name'], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
    ]
