name: Lint Python files

permissions:
  contents: read

on:
  pull_request:
    paths:
      - "server/**"
      - ".github/workflows/*"
  workflow_call:
  workflow_dispatch:

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version-file: "./server/pyproject.toml"

      - name: "Install uv"
        uses: astral-sh/setup-uv@v6
        with:
          cache-dependency-glob: "**/pyproject.toml"

      - name: "Install Python dependencies"
        run: uv sync --locked --all-extras --lint

      - name: "Lint Python"
        run: uv run ruff check . -e

      - name: "Format Python"
        run: uv run ruff format . --check

      - name: "Type Check Python"
        run: uv run mypy
