name: Lint Python files

permissions:
  contents: read

on:
  pull_request:
    paths:
      - "server/**"
      - ".github/workflows/*"
  workflow_call:
  workflow_dispatch:

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v5

      - name: "Install uv"
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.13


      - name: "Install Python dependencies"
        run: uv sync --all-extras --dev

      - name: "Lint Python"
        run: ruff check . -e

      - name: "Format Python"
        run: ruff format . --check

      - name: "Type Check Python"
        run: mypy
